package com.xtc.mall.mapper;

import com.xtc.mall.pojo.Carousel;
import java.util.List;

public interface CarouselMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    int insert(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    Carousel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    List<Carousel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    int updateByPrimaryKey(Carousel record);
}