package com.xtc.mall.pojo;

import java.util.Date;

public class Carousel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.id
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.image_url
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.background_color
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    private String backgroundColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.item_id
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.cat_id
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    private String catId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.type
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.sort
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.is_show
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    private Integer isShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.create_time
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.update_time
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.id
     *
     * @return the value of carousel.id
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.id
     *
     * @param id the value for carousel.id
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.image_url
     *
     * @return the value of carousel.image_url
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.image_url
     *
     * @param imageUrl the value for carousel.image_url
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.background_color
     *
     * @return the value of carousel.background_color
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public String getBackgroundColor() {
        return backgroundColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.background_color
     *
     * @param backgroundColor the value for carousel.background_color
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public void setBackgroundColor(String backgroundColor) {
        this.backgroundColor = backgroundColor == null ? null : backgroundColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.item_id
     *
     * @return the value of carousel.item_id
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.item_id
     *
     * @param itemId the value for carousel.item_id
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.cat_id
     *
     * @return the value of carousel.cat_id
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public String getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.cat_id
     *
     * @param catId the value for carousel.cat_id
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public void setCatId(String catId) {
        this.catId = catId == null ? null : catId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.type
     *
     * @return the value of carousel.type
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.type
     *
     * @param type the value for carousel.type
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.sort
     *
     * @return the value of carousel.sort
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.sort
     *
     * @param sort the value for carousel.sort
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.is_show
     *
     * @return the value of carousel.is_show
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.is_show
     *
     * @param isShow the value for carousel.is_show
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.create_time
     *
     * @return the value of carousel.create_time
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.create_time
     *
     * @param createTime the value for carousel.create_time
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.update_time
     *
     * @return the value of carousel.update_time
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.update_time
     *
     * @param updateTime the value for carousel.update_time
     *
     * @mbg.generated Wed Dec 23 19:22:54 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}